/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "react.native.v6.0.2-23-gc0867f11"
#endif /* AVUTIL_FFVERSION_H */
