/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "react.native.v6.0.2-22-g35329bcc"
#endif /* AVUTIL_FFVERSION_H */
